name = "IsoparametricElements"
uuid = "e04ee02d-1543-450a-8e9b-b1b5ab31155f"
authors = ["Christian Garcia <rojolocco@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"


[compat]
julia = "1"
Plots = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test","SafeTestsets"]
